services:
  mysqldb:
    image: mysql:8
    container_name: mysqldb
    ports:
      - "3303:3306"
    env_file:
      - .mysqlenv
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - spring-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  springboot-app:
    build: .
    container_name: app
    ports:
      - "9090:8080"
    env_file:
      - .env
    depends_on:
      mysqldb:
        condition: service_healthy
    networks:
      - spring-net

networks:
  spring-net:
    name: spring-net
    driver: bridge

volumes:
  mysql-data:
